config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#home"

  get "help" => "static_pages#help"

  get "about" => "static_pages#about"

  get "contact" => "static_pages#contact"

  get "games" => "static_pages#games"

  get "pratice_page" =>"pages#page1"

  get  'signup', to: 'users#new'

  delete 'logout', to: 'sessions#destroy'

  post  'signup_event', to:'events#create'

  resources :users

  resources :sessions, only: [:new,:create,:destroy]

  get "home_search", to:"static_pages#search"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController <  ApplicationController
  def create
    event = Event.new(name: params[:name], phone: params[:phone])
    if event.save
      respond_to do |format|
        format.json {
          render json: {success: true, msg: "恭喜注册成功"}
        }
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def page1
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(:email => sessions_params[:email])
    if user && user.authenticate(sessions_params[:password])
      # view_context.help_methods
      log_in user
      flash[:success]="Successfully Log In"
      redirect_to user_path user
    else
      flash[:danger]="Failed Log In"
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

  private

  def sessions_params
    params.require(:sessions).permit(:email,:password)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def search
    respond_to do |format|
      format.json {
        # render json:User.all.map{|x| x.name}
        # render json: User.where("name like ?","%#{params[:q]}%").map{|x| x.name}
        render json: User.where("name like ?","%#{params[:q]}%").map{|x| {name: x.name,id: x.id}}
        # binding.pry
      }
    end
  end

  def games
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      # binding.pry
      session[:user_id] = @user.id
      flash[:success]="Successfully Signed up"
      redirect_to user_path(@user.id)
      # redirect_to @user
    else
      render "new"
    end
  end

  def show
    @user = User.find params[:id]
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "My Ruby on Rails App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    current_user.present?
  end

end

app/helpers/statc_pages_helper.rb
module StatcPagesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><input type="text" placeholder="搜索"class="form-control white" id="input_search"></li>
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <li>
          <% if logged_in? %>
          <!-- <a class="dropdown-toggle" data-toggle="dropdown">
            Account
          </a> -->
          <%= link_to "Account", '#', class: "dropdown-toggle", "data-toggle" => "dropdown"%>
          <ul class="dropdown-menu">
            <li>
              <%= link_to current_user.name, user_path(current_user.id) %>
            </li>
            <li role="separator" class="divider"></li>
            <li>
              <%= link_to "logout",logout_path, method: :delete %>
            </li>
          </ul>
          <% else %>
            <%=  link_to "Log in", new_session_path %>
          <% end %>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <%= full_title(yield(:title)) %>
    </title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class:"alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>

      <footer class="footer">
        <nav>
          <ul>
            <li><%= link_to "About",   about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
          </ul>
        </nav>
      </footer>
    </div>

  </body>
</html>

app/views/pages/page1.html.erb
<div class="container">
  <div class="asian-persuation">
    <div class="col-sm-10 asian-section1">
      <p class="float-left">BRISBANE</p>
      <p class="float-left text1">SYDENY</p>
      <p class="float-left text1">MELBOURNE</p>
      <p class="float-left text1">ADELAIDE</p>
      <p class="float-left text1">PERTH</p>

    </div>
  </div>

  <div class="text-align-center">
    <h3 class="secion2">
    PV panels are now dominated by Chinese made brands, now it is time for Inverters to dominate the market.
    </h3>

    <p class="secion3">
    Once their was a time when a Chinese made inverter was not trusted, but not now. That has all
    </p>


    <p class="secion3">
    changed as these brands are taking Solar Inverter Industry by storm. With patented
    </p>

    <p class="secion3">
    technologies and breakthrough achievements,Chinese brands are now loudly proud and
    </p>

    <p class="secion3">
    dominate markets all over the world. OSW is uniquely positioned to deliver you these brands
    </p>

    <p class="secion3">
     that will drive your business to new highs.
    </p>


    <p class="secion3">
    Our Key Note Speaker Glen Morris has a lot to say on this subject, as does our MC Anthony
    </p>

    <p class="secion3">
    Buckwell.The event will conclude with complimentary canapes & drinks, and the chance to
    </p>

    <p class="secion3">
    mingle and network with events sponsors and other industry leaders!
    </p>

    <h1>
      Don't believe us? Then come and hear from these incredible brands!
    </h1>
  </div>


  <div class="section4">
    <p class="section5-first section5">
      1. Huawei is a leading solar inverter manufacturer, No.1 in global shipment 2015-2017 totaling 75GW
    </p>

    <p class="section5">
      2. Made for Australia – introducing 29.9KTL inverter for C&I scenario
    </p>

    <p class="section5">
      3. Superior design with game-changing features that maximise energy yield and minimise cost of O&M
    </p>

    <p class="section5">
      4. One-fits-all flexible PV solution for residential rooftops
    </p>

    <button class="section5-btn">
      FIND OUT MORE
    </button>
  </div>

  <div class="section6">
    <p class="section6-picture">
      Sungrow is a global leading inverter solution supplier for renewables with over 79 GW installed worldwide as of Dec 2018. Founded in 1997 by University Professor Cao Renxian, Sungrow is a leader in the research and development of solar inverters, with the largest dedicated R&D team in the industry and a broad product portfolio offering PV inverter solutions and energy storage systems for utility-scale, commercial, and residential applications, as well as internationally recognized floating PV plant solutions. With a strong 22-year track record in the PV space, Sungrow products power installations in over 60 countries, maintaining a worldwide market share of over 15%.
    </p>

    <button class="section6-btn">
      FIND OUT MORE
    </button>
  </div>

  <div class="section7">
    <p class="section7-picture">
      GoodWe will deliver intimate knowledge of its full range of products and detailed knowhow about both
      residential and commercial storage solutions coupled with its ES & ET battery inverters and SBP AC-coupled
      retrofit device. The course also covers technical and sales aspects that assist you in transitioning from
      residential to commercial market. More importantly, find out what kind of added value GoodWe is
      concentrating on for your future.
    </p>

    <button class="section7-btn">
       FIND OUT MORE
    </button>

  </div>

  <div class="section8">
    <div class="col-sm-2 picture col-sm-offset-1">
      <h3>
        BRISBANE
      </h3>
      <%= image_tag("asian_persuasion_practicing/brisbane.png", class:"asian-picture") %>
      <p class="section8-txt">
        1.00pm - 5.00pm Thursday 14/03/2019 Easts League Club
      </p>
    </div>

    <div class="col-sm-2 picture">
      <h3>
        SYDNEY
      </h3>
      <%= image_tag("asian_persuasion_practicing/sydney.png", class:"asian-picture") %>
      <p class="section8-txt">
        1.00pm - 5.00pm Tuesday 19/03/2019 Dooleys Lidcombe Club
      </p>
    </div>

    <div class="col-sm-2 picture">
      <h3>
        MELBOURNE
      </h3>
      <%= image_tag("asian_persuasion_practicing/melbourne.png", class:"asian-picture") %>
      <p class="section8-txt">
        1.00pm - 5.00pm Monday 25/03/2018 The Kew Gold Club
      </p>
    </div>

    <div class="col-sm-2 picture">
      <h3>
        ADELAIDE
      </h3>
      <%= image_tag("asian_persuasion_practicing/adelaide.png", class:"asian-picture") %>
      <p class="section8-txt">
        1.00pm - 5.00pm Friday 29/03/2019 Royal Adelaide Golf Club
      </p>
    </div>

    <div class="col-sm-2 picture">
      <h3>
        PERTH
      </h3>
      <%= image_tag("asian_persuasion_practicing/perth.png", class:"asian-picture") %>
      <p class="section8-txt">
        12.30pm - 5.00pm Wednesday 10/04/2019 Royal Perth Golf Club
      </p>
    </div>

    <button class="section8-btn" data-toggle="modal" data-target="#eventModal">
      REGISTER NOW
    </button>
  </div>

  <div class="section9">
    <div class="col-sm-3 col-sm-offset-1 picture">
      <%= image_tag("asian_persuasion_practicing/glen_morris.png",class:"section9-picture")%>
    </div>
    <div class="col-sm-8 text1">
      <h3 class="title">Glen Morris</h3>
      <p>
        Glen has worked in electronics, renewable energy, software development, web hosting and vocational training. His current passion for training practitioners of renewable energy brings together his wide range of skills. Glen is very passionate about making a difference - helping the community move towards a more sustainable planet.
      </P>
      <p>Glen is the General Manager for SmartLabEnergy and owner of both Solaris Pty Ltd & SolarQuip.</p>
    </div>
  </div>

  <div class="section10">
    <div class="col-sm-8 text1">
      <h3 class="title">Anthony Buckwell</h3>
      <p>
        Anthony has spent over 20 years engineering in true leading edge technologies. Firstly on the first 3G mobile telecommunications networks and then the last 10 years in the Renewable Energy sector.
      </p>
      <p>
        Holding a Bachelor of Engineering in Microelectronics (Comms), full CEC Design and Installation accreditation for on grid and Standalone Power Systems as well as a Electrical Mechanics license.
      </p>
      <p>
        Anthony has been the Technical Development Manager for One Stop Warehouse these last 3 years.
      </p>
    </div>
    <div class="col-sm-3 col-sm-offset-1 picture">
      <%= image_tag("asian_persuasion_practicing/anthony_buckwell.png")%>
    </div>
  </div>

    <!-- Modal -->
    <div class="modal fade" id="eventModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Modal title</h4>
          </div>
          <div class="modal-body">
            <div class="section11" style="width:200px;height:200px;text-align:center;margin: auto;">
              <div class="rua!">
                <%= form_tag "/signup_event" %>
                  <%= label_tag("name") %> <br>
                  <%= text_field_tag(:name) %><br>
                  <%= label_tag("phone") %><br>
                  <%= text_field_tag(:phone) %><br>
                  <br>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= submit_tag "Sign up!", id: "xxxx",  class:"btn btn-primary", style:"width: 200px;float:right;margin-left:15px;" %>
          </div>
        </div>
      </div>
    </div>

</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize( object.errors.count, "error" ) %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/static_pages/games.html.erb
<div id="game_table">
  <div id="desk">
    <div id="cards">
      <div class="card">
        <div class="face front"></div>
        <div class="face back"></div>
      </div>
    </div>
  </div>
</div>
<script>
  $(function(){
    // console.log(index)
    var game={};
    game.matchingGames={};
    game.matchingGames.cardWidth=80;
    game.matchingGames.cardHeight=120;
    game.matchingGames.deck=[
        "cardAK","cardAK",
        "cardAQ","cardAQ",
        "cardAJ","cardAJ",
        "cardBK","cardBK",
        "cardBQ","cardBQ",
        "cardBJ","cardBJ"
    ];

    var card=$(".card");
    for (var i=0;i<11;i++){
      card.clone().appendTo("#cards");
    }
    game.matchingGames.deck.sort(function(){ return 0.5 - Math.random() })
    $(".card").each(function(index){
      // console.log(index)
      $(this).find(".back").addClass(game.matchingGames.deck[index])
      $(this).css({
        "left":(game.matchingGames.cardWidth+50)*(index%4)+"px",
        "top":(game.matchingGames.cardHeight+60)*Math.floor(index/4)+"px"
        // console.log(game.matchingGames.cardWidth)*(index%4));
      })
    });
    $(".card").on('click', function(){
      $(this).find(".front").css("z-index", 1)
      $(this).find(".back").css("z-index", 2);
    });
  });
</script>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>欢迎</h1>

  <%= link_to "Sign up now!" , signup_path, class: "btn btn-large btn-primary" %>
</div>

app/views/users/new.html.erb
<% provide( :title, 'Sign up' ) %>
<h1>Sign up</h1>
<div class="row signup">
  <div class="span6 col-sm-4 col-md-offset-4">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' , object: f.object %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.label :email %>
        <%= f.text_field :email %>
        <%= f.label :password %>
        <%= f.password_field :password %>
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %>
        <%= f.submit "Create my account" , class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.name %>